name: "Build & Deploy to Netlify"
on:
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12

    - name: Install unstable channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing NixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        nix --version
        cat /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - uses: cachix/cachix-action@v8
      with:
        name: nixos-homepage
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Building nixos.org
      run: |
        nix build
        mkdir build
        cp -RL ./result/* ./result/.well-known/ ./build/

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        production-branch: 'master'
        publish-dir: './build'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deploy from GitHub Actions'
        enable-pull-request-comment: true
        enable-commit-comment: true
        enable-commit-status: true
        overwrites-pull-request-comment: false
      if: github.repository == 'NixOS/nixos-homepage'

